lib/bisignal_web/router.ex
defmodule BisignalWeb.Router do
  use BisignalWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", BisignalWeb do
    pipe_through :api

    get "/participants", ApiController, :participants
    get "/participants/:time", ApiController, :current_by_time
    get "/participants_recent", ApiController, :current
    get "/participants_recent_near/:lng/:lat", ApiController, :nearby_current
    get "/participants_last_seen_near/:lng/:lat", ApiController, :nearby
    get "/participants_last_seen/:distance/meters_from/:lng/:lat", ApiController, :within_distance
    get "/participants/:distance/meters_from/:lng/:lat/in_last/:time/minutes", ApiController, :within_distance_by_time

    get "/routes_all", ApiController, :routes
    get "/routes_near/:lng/:lat", ApiController, :routes_nearby
    get "/routes_within/:distance/of/:lng/:lat", ApiController, :routes_within_distance
  end

  scope "/", BisignalWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/help", PageController, :help
    resources "/users", UserController, only: [:index, :new, :create, :delete, :show] do
      get "/participation", ParticipantController, :show_by_user
      get "/participation/:id", ParticipantController, :show
      get "/route_details", RouteDetailController, :show_by_user
      get "/route_details/new", RouteDetailController, :new
      get "/route_details/:id", RouteDetailController, :user_show
      post "/route_details/", RouteDetailController, :create
      delete "/route_details/:id", RouteDetailController, :delete_by_user 
    end

    get "/route_details/:id", RouteDetailController, :show
    get "/route_details/", RouteDetailController, :index
    post "/route_details/:id/join", ParticipantController, :create
    delete "/route_details/:id/leave", ParticipantController, :delete
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

end

lib/bisignal_web/views/layout_view.ex
defmodule BisignalWeb.LayoutView do
  use BisignalWeb, :view
end

lib/bisignal_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content=", initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">

    <title>BiSignal</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand">BiSignal</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse navbar-right">
          <ul class="nav navbar-nav">
            <li><a href="<%= page_path @conn, :index %>">Track</a></li>
            <li><a href="<%= route_detail_path @conn, :index %>">View All Rides</a></li>
            <%= if @current_user do %>
            <li><a href="<%= user_participant_path @conn, :show_by_user, @current_user %>">Broadcast!</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="<%= user_path(@conn, :show, @current_user.id) %>">Account</a></li>
                <li><%= link "Create New Ride", to: user_route_detail_path(@conn, :new, @current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link "Logout", to: session_path(@conn, :delete, @current_user), method: :delete %></li>
              </ul>
            </li>
            <% else %>
            <li><a href="<%= user_path @conn, :new %>">New user</a></li>
            <li><a href="<%= session_path @conn, :new %>">Login</a></li>
            <% end %>
            <li><a href="<%= page_path @conn, :help %>">Help</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div> <!-- /container -->
    <script>
      window.userToken = "<%= assigns[:user_token] %>";
    </script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
            crossorigin="anonymous">
    </script>
  </body>
</html>