lib/bisignal_web/router.ex
defmodule BisignalWeb.Router do
  use BisignalWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Phauxth.Authenticate
    plug :put_user_token
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", BisignalWeb do
    pipe_through :api

    get "/participants", ApiController, :participants
    get "/participants/:time", ApiController, :current_by_time
    get "/participants_recent", ApiController, :current
    get "/participants_recent_near/:lng/:lat", ApiController, :nearby_current
    get "/participants_last_seen_near/:lng/:lat", ApiController, :nearby
    get "/participants_last_seen/:distance/meters_from/:lng/:lat", ApiController, :within_distance
    get "/participants/:distance/meters_from/:lng/:lat/in_last/:time/minutes", ApiController, :within_distance_by_time

    get "/routes_all", ApiController, :routes
    get "/routes_near/:lng/:lat", ApiController, :routes_nearby
    get "/routes_within/:distance/of/:lng/:lat", ApiController, :routes_within_distance
  end

  scope "/", BisignalWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/help", PageController, :help
    resources "/users", UserController, only: [:index, :new, :create, :delete, :show] do
      get "/participation", ParticipantController, :show_by_user
      get "/participation/:id", ParticipantController, :show
      get "/route_details", RouteDetailController, :show_by_user
      get "/route_details/new", RouteDetailController, :new
      get "/route_details/:id", RouteDetailController, :user_show
      post "/route_details/", RouteDetailController, :create
      delete "/route_details/:id", RouteDetailController, :delete_by_user 
    end

    get "/route_details/:id", RouteDetailController, :show
    get "/route_details/", RouteDetailController, :index
    post "/route_details/:id/join", ParticipantController, :create
    delete "/route_details/:id/leave", ParticipantController, :delete
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  defp put_user_token(conn, _) do
    if current_user = conn.assigns[:current_user] do
      token = Phoenix.Token.sign(conn, "user socket", current_user.id)
      assign(conn, :user_token, token)
    else
      conn
    end
  end

end

lib/bisignal/ride/route_detail.ex
defmodule Bisignal.Ride.RouteDetail do
  use Ecto.Schema
  import Ecto.Changeset
  alias Bisignal.Ride.RouteDetail

  @derive {Poison.Encoder, only: [:name, :datetime, :start_name, :end_name, :start, :end]}
  schema "route_details" do
    field :name, :string
    field :datetime, :utc_datetime
    field :start, Geo.Geometry
    field :start_json, :string, virtual: true
    field :start_name, :string
    field :end, Geo.Geometry
    field :end_json, :string, virtual: true
    field :end_name, :string
    belongs_to :user, Bisignal.Accounts.User

    timestamps()
  end

  @doc false
  def changeset(%RouteDetail{} = route_detail, attrs) do
    route_detail
    |> cast(attrs, [:start, :start_name, :end, :end_name, :datetime, :name, :user_id])
    |> validate_required([:start, :end, :datetime, :name, :user_id])
  end

  def encode_model(geometry) do
    %RouteDetail{geometry | start: Geo.JSON.encode(geometry.start), end: Geo.JSON.encode(geometry.end) }
  end

  defimpl Poison.Encoder, for: Bisignal.Ride.RouteDetail do
    def encode(geometry, options) do
      geometry = RouteDetail.encode_model(geometry)
      Poison.Encoder.Map.encode(Map.take(geometry, [:name, :datetime, :start, :end, :start_name, :end_name]), options)
    end
  end
end

lib/bisignal_web/controllers/route_detail_controller.ex
defmodule BisignalWeb.RouteDetailController do
  use BisignalWeb, :controller

  import BisignalWeb.Authorize
  import Ecto.Query, warn: false

  alias Bisignal.Ride
  alias Bisignal.Ride.RouteDetail
  alias Bisignal.Accounts.User
  alias Bisignal.Accounts

  plug :user_check when action in [:new, :user_show]
  plug :user_id_check when action in [:create, :edit, :update, :delete_by_user, :show_by_user]

  def index(conn, _params) do
    route_details = Ride.list_route_details()
    render(conn, "list_index.html", route_details: route_details)
  end

  def new(conn, _params) do
    changeset = Ride.change_route_detail(%RouteDetail{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user_id" => user_id, "route_detail" => route_detail_params}) do
    assoc_user = Map.put(route_detail_params, "user_id", user_id)
    case Ride.create_route_detail(assoc_user) do
      {:ok, route_detail} ->
        user = Accounts.get(user_id)
        conn
        |> put_flash(:info, "Route detail created successfully.")
        |> redirect(to: user_route_detail_path(conn, :user_show, user_id, route_detail))
      {:error, %Ecto.Changeset{} = changeset} ->
        IO.inspect changeset
        changeset_without_geo = RouteDetail.changeset(changeset.data, Map.merge(changeset.changes, %{start: nil, end: nil}))
        conn
        |> put_flash(:error, "Something went wrong! Some fields may not have been filled in. Please try again.")
        |> render("new.html", changeset: changeset_without_geo)
    end
  end

  def user_show(conn, %{"user_id" => user_id,"id" => id}) do
    case Ride.get_users_route_detail(user_id, id) do
      nil ->
        conn
        |> put_flash(:info, "No Route Found")
        |> redirect(to: page_path(conn, :index))
      route_detail ->
        user = Accounts.get(user_id)
        participants = Ride.get_participant_names(id)
        render(conn, "show.html", route_detail: route_detail, participants: participants, user: user)
    end
  end

  def show(conn, %{"id" => id}) do
    case Ride.get_route_detail!(id) do
      nil ->
        conn
        |> put_flash(:info, "No Route Found")
        |> redirect(to: route_detail_path(conn, :index))
      route_detail ->
        participants = Ride.get_participant_names(id)
        render(conn, "show.html", route_detail: route_detail, participants: participants)
    end
  end

  def show_by_user(conn, %{"user_id" => user_id}) do
    route_details = Ride.list_users_routes(user_id)
    user = Accounts.get(user_id)
    render(conn, "user_index.html", route_details: route_details, user: user)
  end

  def delete_by_user(conn, %{"user_id" => user_id, "id" => id}) do
    route_detail = Ride.get_route_detail!(id)
    {:ok, _route_detail} = Ride.delete_route_detail(route_detail)
    conn
    |> put_flash(:info, "Route detail deleted successfully.")
    |> redirect(to: user_path(conn, :show, user_id))
  end
end

lib/bisignal_web/views/route_detail_view.ex
defmodule BisignalWeb.RouteDetailView do
  use BisignalWeb, :view
end

lib/bisignal_web/templates/route_detail/form.html.eex
<div class="panel panel-success">
  <div class="panel-heading">
    <h2>Add New Ride</h2>
    <p>Here you complete the form to create a new Ride which is viewable to other site users. Other users may choose to participate in Rides you organise. If you are going to attend this ride, don't forget to join as a participant by going to <i>View All Rides</i>, selecting your Ride and choosing <i>Join</i>.</p>
    <%= form_for @changeset, @action, fn f -> %>
    <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
    <% end %>
  </div>
  <div class="panel-body">
    <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
    </div>

    <div class="form-group">
    <%= hidden_input f, :start, id: "start" %>
    <%= hidden_input f, :end, id: "end" %>
    <%= hidden_input f, :waypoints, id: "waypoints" %>
    <%= hidden_input f, :start_name, id: "start_name" %>
    <%= hidden_input f, :end_name, id: "end_name" %>




    <%= render "routepicker.html", conn: @conn %>
    </div>

    <div class="form-group">
    <%= label f, :datetime, class: "control-label" %>
    <%= datetime_select f, :datetime, class: "form-control" %>
    <%= error_tag f, :datetime %>
    </div>

  </div>
  <div class="panel-footer">
  <div class="row">
    <div class="col-md-3">
      
    </div>
    <div class="col-md-3">
      <script>
        document.write('<a class="btn btn-danger btn-block" href="' + document.referrer + '">Cancel</a>');
      </script>
    </div>
    <div class="col-md-3">
      <%= submit "Submit", class: "btn btn-success btn-block" %>
    </div>
    <div class="col-md-3">
      
    </div>
  </div>





    <% end %>
  </div>
</div>

<script>
  // here for testing only
        // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
var route = {};
var directionsInfo;

var start = document.getElementById('start');
var end = document.getElementById('end');
var waypoints = document.getElementById('waypoints');
var originInput = document.getElementById('origin-input');
var destinationInput = document.getElementById('destination-input');

function initMap() {
  map = new google.maps.Map(document.getElementById('map'), {
    mapTypeControl: false,
    center: {lat: 51.5074, lng: 0.1278},
    zoom: 3
  });
  new AutocompleteDirectionsHandler(map);
}

 /**
  * @constructor
 */
 // Based on the Place Autocomplete Example from Google Maps JavaScript API
 // https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-directions
function AutocompleteDirectionsHandler(map) {
  this.map = map;
  this.originPlaceId = null;
  this.destinationPlaceId = null;
  this.travelMode = 'BICYCLING'

  this.directionsService = new google.maps.DirectionsService;
  this.directionsService.route({'travelMode': google.maps.DirectionsTravelMode.BICYCLING})

  this.directionsDisplay = new google.maps.DirectionsRenderer({'draggable':true});
  this.directionsDisplay.setMap(map);
  directionsInfo = this.directionsDisplay;

  var originAutocomplete = new google.maps.places.Autocomplete(
      originInput, {placeIdOnly: true});
  var destinationAutocomplete = new google.maps.places.Autocomplete(
      destinationInput, {placeIdOnly: true});

  this.setupPlaceChangedListener(originAutocomplete, 'ORIG');
  this.setupPlaceChangedListener(destinationAutocomplete, 'DEST');
  this.directionsDisplay.addListener('directions_changed', function() {
    saveRoute(directionsInfo)
  })

  this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(originInput);
  this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(destinationInput);
}

AutocompleteDirectionsHandler.prototype.setupPlaceChangedListener = function(autocomplete, mode) {
  var me = this;
  autocomplete.bindTo('bounds', this.map);
  autocomplete.addListener('place_changed', function() {
    var place = autocomplete.getPlace();
    if (!place.place_id) {
      window.alert("Please select an option from the dropdown list.");
      return;
    }
    if (mode === 'ORIG') {
      me.originPlaceId = place.place_id;
    } else {
      me.destinationPlaceId = place.place_id;
    }
    me.route();
  });
};

AutocompleteDirectionsHandler.prototype.route = function() {
  if (!this.originPlaceId || !this.destinationPlaceId) {
    return;
  }
  var me = this;
  this.directionsService.route({
    origin: {'placeId': this.originPlaceId},
    destination: {'placeId': this.destinationPlaceId},
    travelMode: this.travelMode
  }, function(response, status) {
    if (status === 'OK') {
      me.directionsDisplay.setDirections(response);
    } else {
      window.alert('Directions request failed due to ' + status);
    }
  });
};

var saveRoute = function (directionsDisplay) {
    var final_waypoints={}, via;
    var route_legs = directionsDisplay.directions.routes[0].legs[0];
    if(!route_legs) {
      return
    }
    //creating GeoJSON start and end points
    route.start = {'type': 'Point', 'coordinates': [route_legs.start_location.lng(), route_legs.start_location.lat()]}
    route.end = {'type': 'Point', 'coordinates': [route_legs.end_location.lng(), route_legs.end_location.lat()]}
    var via = route_legs.via_waypoints 

    //not used
    for(var i = 0; i < via.length; i++) {
      final_waypoints[''+i+''] = {'type': 'Point', 'coordinates': [via[i].lng(), via[i].lat()]}
    }

    route.waypoints = final_waypoints; 
    start_name.value = originInput.value
    end_name.value = destinationInput.value
    
    //binding GeoJSON to hidden input fields
    waypoints.value = JSON.stringify(route.waypoints)
    start.value = JSON.stringify(route.start)
    end.value = JSON.stringify(route.end)
}

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZb6It08HrypHnxdYwZenAUtnlsitIOes&libraries=places&callback=initMap"
    async defer></script>











  

lib/bisignal_web/templates/route_detail/list_index.html.eex
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2>All Rides</h2>
    <p>A complete listing of all Rides organised by the users of BiSignal. To find out more information, or to register your intention to participate, choose <i>View All Ride Info</i>.</p>
  </div>
  <div class="panel-body">
    <%= if Enum.empty?(@route_details) do %>
    <b> No Rides found. </b>
    <% else %>
      <%= for route_detail <- @route_details do %>
          <div class="panel panel-default ">
            <div class="panel-heading">
              <div class="text-center">
                <div class="row">
                  <div class="col-sm-9">
                      <h3 class="pull-left">
                        <%= link route_detail.name, to: route_detail_path(@conn, :show, route_detail) %>    
                      </h3>
                  </div>
                  <div class="col-sm-3">
                    <h4 class="pull-right">
                    <small>Scheduled for <em><%= route_detail.datetime.day %>/<%= route_detail.datetime.month %>/<%= route_detail.datetime.year %></em></small>
                    </h4>
                  </div>
                </div>
              </div>
            </div>  
            <div class="panel-body">
                <div class="row">
                  <div class="col-md-4">
                    <p><strong>From</strong> <%= route_detail.start_name %></p>
                  </div>
                  <div class="col-md-4">
                    <p><strong>To</strong> <%= route_detail.end_name %></p>
                  </div>
                  <div class="col-md-4">
                    
                  </div>
                </div>
            </div>
                
            <div class="panel-footer">
            <div class="row text-center">
              <div class="col-md-4">
                <span><%= link "View Creator's Profile", to: user_path(@conn, :show, route_detail.user_id), class: "btn btn-default btn-block" %></span>
              </div>
              <div class="col-md-4">
                
              </div>
              <div class="col-md-4">
                <span><%= link "View All Ride Info", to: route_detail_path(@conn, :show, route_detail), class: "btn btn-info btn-block" %></span>
              </div>
            </div>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>
  <div class="panel-footer">
    <div class="row text-center"> 
      <script>
        document.write('<a class="btn btn-default" href="' + document.referrer + '">Back</a>');
      </script>
    </div>
  </div>


</div>

lib/bisignal_web/templates/route_detail/new.html.eex
<%= render "form.html", Map.put(assigns, :action, user_route_detail_path(@conn, :create, @current_user)) %>

lib/bisignal_web/templates/route_detail/routepicker.html.eex
    <input id="origin-input" class="controls" type="text"
        placeholder="Enter Ride starting point">
    <input id="destination-input" class="controls" type="text"
        placeholder="Enter Ride destination">
    <div id="map" style="clear:both; height:30em"></div> 
        
    <script src='<%= static_path(@conn, "/js/routepicker.js") %>'></script>

lib/bisignal_web/templates/route_detail/show.html.eex
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="text-center">
      <div class="row">
        <div class="col-sm-9">
          <h2 class="pull-left"><%= @route_detail.name %></h2>
        </div>
        <div class="col-sm-3">
          <h4 class="pull-right">
          <small>Scheduled for <em><%= @route_detail.datetime.day %>/<%= @route_detail.datetime.month %>/<%= @route_detail.datetime.year %></em></small>
            <%= if @current_user do %>
              <%= if @current_user.name in @participants do %>
                <p><span><%= link "Leave", to: participant_path(@conn, :delete, @route_detail), 
                                            method: :delete, data: [confirm: "Want to Leave this Ride?"], 
                                              class: "btn btn-danger btn-lg btn-block" %></span></p>
              <% else %>
                <p><span><%= link "Join", to: participant_path(@conn, :create, @route_detail), 
                                            method: :post, data: [confirm: "Want to Join this Ride?"], 
                                              class: "btn btn-success btn-lg btn-block" %></span></p>
              <% end %>
            <% end %>
          </h4>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <p>A trip between <%= @route_detail.start_name %> and <%= @route_detail.end_name %>.</p>
    <div id="map" style="height:30em"></div>
  </div>
  <div class="panel-footer">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-4">
      <script>
        document.write('<a class="btn btn-default btn-block" href="' + document.referrer + '">Back</a>');
      </script>
    </div>
    <div class="col-md-4">
          <details>
       <summary class="btn btn-default btn-block">Show Participants</summary>
        <ul>
          <%= if Enum.empty?(@participants) do %>
            <b> None </b>
          <% else %>
            <%= for participant <- @participants do %>
              <li><b><%= participant %></b></li>
            <% end %>
          <% end %>
        </ul>
    </details>
    </div>
    <div class="col-md-2"></div>
  </div>
  </div>
</div>
<div id="coords" 
  data-start="<%= Geo.JSON.encode(@route_detail.start) |> Poison.encode! %>"
  data-end="<%= Geo.JSON.encode(@route_detail.end) |> Poison.encode! %>" 
/>

<script src='<%= static_path(@conn, "/js/displayroute.js") %>'></script>

<script>
  // here for testing only
    var coords = document.getElementById('coords')
    var start_point = JSON.parse(coords.getAttribute('data-start'));
    var end_point = JSON.parse(coords.getAttribute('data-end'));
    var start_lng = start_point.coordinates[0];
    var start_lat = start_point.coordinates[1];
    var end_lng = end_point.coordinates[0];
    var end_lat = end_point.coordinates[1];

    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            mapTypeControl: false,
            zoom: 3
        });
        displayRoute();
    }


    function displayRoute() {
        var start = new google.maps.LatLng(start_lat, start_lng);
        var end = new google.maps.LatLng(end_lat, end_lng);

        var directionsDisplay = new google.maps.DirectionsRenderer();// also, constructor can get "DirectionsRendererOptions" object
        directionsDisplay.setMap(map); // map should be already initialized.

        var request = {
            origin : start,
            destination : end,
            travelMode : google.maps.TravelMode.BICYCLING
        };

        var directionsService = new google.maps.DirectionsService(); 
        directionsService.route(request, function(response, status) {
            if (status == google.maps.DirectionsStatus.OK) {
                directionsDisplay.setDirections(response);
            }
        });
    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZb6It08HrypHnxdYwZenAUtnlsitIOes&libraries=places&callback=initMap"
    async defer></script>

lib/bisignal_web/templates/route_detail/user_index.html.eex
<h2><%= @user.name %>'s Rides</h2>

<%= if Enum.empty?(@route_details) do %>
<h3> No Rides found. </h3>
<% else %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Datetime</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for route_detail <- @route_details do %>
    <tr>
      <td><%= route_detail.name %></td>
      <td><%= route_detail.start_name %></td>
      <td><%= route_detail.end_name %></td>
      <td><%= route_detail.datetime %></td>
      <td class="text-right">
        <span><%= link "Show", to: user_route_detail_path(@conn, :user_show, @user, route_detail), class: "btn btn-default btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<% end %>

<p><span><%= link "Add New Ride", to: user_route_detail_path(@conn, :new, @user), class: "btn btn-success btn-xs" %></span></p>

lib/bisignal_web/templates/route_detail/user_show.html.eex
  <p><strong>Name:</strong> <%= @route_detail.name %></p>
  
  <div id="coords" 
    data-start="<%= Geo.JSON.encode(@route_detail.start) |> Poison.encode! %>"
    data-end="<%= Geo.JSON.encode(@route_detail.end) |> Poison.encode! %>" 
  />
  <div id="map" style="clear:both; height:30em"></div>

  <p><strong>Start Name:</strong> <%= @route_detail.start_name %></p>

  <p><strong>End Name:</strong> <%= @route_detail.end_name %></p>

  <p><strong>Datetime:</strong> <%= @route_detail.datetime %></p>

  <p><strong>Organiser:</strong> <%= link @user.name, to: user_path(@conn, :show, @user), method: :get %></p>

<%= if @user.id == @current_user.id do %>
  <p><span><%= link "Delete", to: user_route_detail_path(@conn, :delete_by_user, @user, @route_detail), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger" %></span></p>
<% end %>

<script>
    document.write('<a class="btn btn-info" href="' + document.referrer + '">Back</a>');
</script>

<link rel="stylesheet" href='<%= static_path(@conn, "/css/routepicker.css") %>'>
<script src='<%= static_path(@conn, "/js/displayroute.js") %>'></script>


<script>
  //  testing only
var coords = document.getElementById('coords')
var start_point = JSON.parse(coords.getAttribute('data-start'));
var end_point = JSON.parse(coords.getAttribute('data-end'));
var start_lng = start_point.coordinates[0];
var start_lat = start_point.coordinates[1];
var end_lng = end_point.coordinates[0];
var end_lat = end_point.coordinates[1];

function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
        mapTypeControl: false,
        zoom: 3
    });
    displayRoute();
}

function displayRoute() {
    var start = new google.maps.LatLng(start_lat, start_lng);
    var end = new google.maps.LatLng(end_lat, end_lng);

    var directionsDisplay = new google.maps.DirectionsRenderer();// also, constructor can get "DirectionsRendererOptions" object
    directionsDisplay.setMap(map); // map should be already initialized.

    var request = {
        origin : start,
        destination : end,
        travelMode : google.maps.TravelMode.BICYCLING
    };

    var directionsService = new google.maps.DirectionsService(); 
    directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
            directionsDisplay.setDirections(response);
        }
    });
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZb6It08HrypHnxdYwZenAUtnlsitIOes&libraries=places&callback=initMap"
    async defer></script>